Payment with Pix
rafaelcalves/gerencia-sao-vicente-dev3 pull request #3
Opened 2021-05-24 23:26 UTC by FabianeKuhn

2021-05-25 23:41 UTC, rafaelcalves requested changes
Marcando pra esperar alterações mas aberto a discussão sobre o comentário adicionado

2021-05-25 23:41 UTC, rafaelcalves commented on src/main/webapp/WEB-INF/jsp/pix.jsp
> +            function myFunctionCNPJ() {
Isso talvez fique mais legal em um arquivo separado js tal qual o css

2021-05-26 02:08 UTC, FabianeKuhn commented on src/main/webapp/WEB-INF/jsp/pix.jsp
> +            function myFunctionCNPJ() {
Alterações feitas

2021-05-26 02:26 UTC, rafaelcalves approved these changes

2021-05-26 02:26 UTC, merged